version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot-img
    container_name: bot-con
#    depends_on:
#      db:
#        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - TELEGRAM_TOKEN

#  db:
#    image: postgres:latest
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    env_file:
#      - ./.env
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASS}