services:
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    ports:
      - "80:80"
    volumes:
      - /etc/letsenrypt:/etc/letsenrypt
    command: certonly --standalone --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN}